CREATE TABLE IF NOT EXISTS "urls" (
    URL_ID SERIAL PRIMARY KEY NOT NULL UNIQUE,
    USER_ID SERIAL,
    FULL_URL TEXT NOT NULL UNIQUE,
    SHORT_URL VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY(USER_ID) REFERENCES "users" ON DELETE CASCADE
)