CREATE TABLE IF NOT EXISTS "users" (
    USER_ID SERIAL PRIMARY KEY NOT NULL UNIQUE,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL UNIQUE
);